// ============================================================================
// maestrina_collect.js — Maestrina collector, mongosh mode (low friction)
// Version: 2.1.0   |   Output contract: maestrina_output.schema.json v2.1.0
// Repo: https://github.com/carimeb/Maestrina
// ============================================================================
//
// WHAT THIS SCRIPT IS
//   Read-only health-check collector for MongoDB deployments (replica set,
//   sharded cluster, or standalone — self-hosted or Atlas). It produces a
//   single JSON file that the Maestrina dashboard (dashboard.html) renders.
//   It is the low-friction companion to atlas_healthcheck.py (Atlas Admin
//   API mode): no API key needed, only a database user, run by your own DBA.
//
// HOW TO RUN (~2-3 minutes, most of it a deliberate sampling pause)
//   mongosh "mongodb+srv://your-cluster.example.net/" \
//           --username <dbUser> --file maestrina_collect.js
//
//   The password is requested interactively by mongosh — it is NEVER written
//   in this file or in the output. Do not edit this file: because it needs no
//   editing, the file you execute can be hash-compared with the published
//   version at the repo above.
//
//   Recommended user privileges: clusterMonitor + readAnyDatabase.
//   Anything the user cannot run is skipped and reported in the "errors"
//   section of the output — collection never aborts on a single failure.
//
// OPTIONS (environment variables — never edit the script)
//   MAESTRINA_SAMPLE_SECONDS   Seconds between the two in-run samples used to
//                              compute real ops/s (default 120; 0 disables the
//                              second sample and falls back to uptime average).
//   MAESTRINA_PSEUDO=1         Pseudonymize namespaces, hosts, database and
//                              index names (sequential labels: ns_001, host_A).
//                              The CLUSTER NAME is intentionally never masked:
//                              it is the navigation key that lets findings be
//                              located and communicated in multi-cluster
//                              environments. The name mapping is written to a
//                              separate local file that STAYS WITH YOU — never
//                              send it.
//   MAESTRINA_BASELINE_FILE    Path to a pre-go-live sizing JSON (produced by
//                              the workload-fingerprinting exercise). Embedded
//                              verbatim for the realized-vs-forecast chart.
//   MAESTRINA_OUT              Output file path (default:
//                              ./maestrina_output_<cluster>_<timestamp>.json).
//   MAESTRINA_DEBUG=1          Also write maestrina_debug_<timestamp>.json:
//                              execution trace (every command attempted, with
//                              timing and success/failure), environment info,
//                              and the errors list. Contains NO collected data.
//                              RECOMMENDED during the field-test phase — if
//                              anything looks wrong, send this file back to
//                              the Maestrina maintainer along with the output.
//
// IF THE SCRIPT CRASHES
//   A maestrina_crash_<timestamp>.json file is written automatically to the
//   current directory with the failure phase, a redacted stack trace, and the
//   execution trace. Send that file back — it is what makes the bug fixable
//   without access to your environment. It contains no collected data.
//
// WHAT IT COLLECTS (operational metadata and statistics ONLY)
//   - serverStatus counters (opcounters, cache, tickets, page faults)
//   - Replication state and lag; oplog window
//   - Database / collection / index SIZES and index USAGE counters
//   - Connection statistics; filesystem usage percent as reported by dbStats
//   - Sharded-cluster distribution from config METADATA via mongos (approach
//     credited to Felipe Scabral's msizer-mongodb:
//     https://github.com/felipesscabral/msizer-mongodb)
//
// WHAT IT NEVER COLLECTS
//   - Document contents / application business data
//   - Query predicate values or query shapes
//   - User accounts or credentials
//   - Personally identifiable information
//   The output file is plain JSON — inspect it (and have your security team
//   inspect it) before sending. That is the intended workflow.
//
// ============================================================================

(function main() {
  'use strict';

  const VERSION = '2.1.0';
  const SCHEMA_VERSION = '2.1.0';
  const TOP_NAMESPACES_LIMIT = 10;
  const UNUSED_INDEXES_LIMIT = 25;

  const fs = require('fs');
  const path = require('path');

  // --------------------------------------------------------------------- //
  // Options (env only — the script file itself is never edited)           //
  // --------------------------------------------------------------------- //
  const env = (typeof process !== 'undefined' && process.env) ? process.env : {};
  const SAMPLE_SECONDS = env.MAESTRINA_SAMPLE_SECONDS !== undefined
    ? Math.max(0, parseInt(env.MAESTRINA_SAMPLE_SECONDS, 10) || 0)
    : 120;
  const PSEUDO = env.MAESTRINA_PSEUDO === '1';
  const BASELINE_FILE = env.MAESTRINA_BASELINE_FILE || null;
  const OUT_PATH_ENV = env.MAESTRINA_OUT || null;
  const DEBUG = env.MAESTRINA_DEBUG === '1';

  // --------------------------------------------------------------------- //
  // Error collection + diagnostics — never abort on a single failure      //
  // --------------------------------------------------------------------- //
  const errors = [];
  const trace = [];              // every command attempted: source, ok, ms
  let phase = 'init';            // last phase reached (for crash reports)
  const envInfo = {              // filled in as detection progresses
    node_version: (typeof process !== 'undefined' && process.version) || null,
    mongodb_version: null,
    topology: null
  };

  function redact(msg) {
    // Strip anything that looks like a connection string or user:pass@host
    return String(msg)
      .replace(/mongodb(\+srv)?:\/\/\S+/gi, 'mongodb://<redacted>')
      .replace(/\/\/[^\s\/@]+@/g, '//<redacted>@');
  }

  function attempt(source, fn) {
    const t0 = Date.now();
    try {
      const r = fn();
      trace.push({ source: source, ok: true, ms: Date.now() - t0 });
      return r;
    } catch (e) {
      trace.push({ source: source, ok: false, ms: Date.now() - t0 });
      errors.push({
        source: source,
        detail: redact(e && e.message ? e.message : e),
        at: new Date().toISOString()
      });
      return null;
    }
  }

  function writeDiagnostics(kind, fatal) {
    // Diagnostics contain NO collected data: only the execution trace,
    // environment/option info, the errors list, and (on crash) a redacted
    // stack trace. Safe to send back to the Maestrina maintainer.
    try {
      const stamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
      const diagPath = path.join(process.cwd(),
        'maestrina_' + kind + '_' + stamp + '.json');
      fs.writeFileSync(diagPath, JSON.stringify({
        maestrina_diagnostics: true,
        kind: kind,
        collector: { name: 'maestrina_collect.js', version: VERSION },
        schema_version: SCHEMA_VERSION,
        generated_at: new Date().toISOString(),
        last_phase: phase,
        environment: envInfo,
        options: {
          sample_seconds: SAMPLE_SECONDS,
          pseudonymization_enabled: PSEUDO,
          baseline_file_provided: !!BASELINE_FILE,
          output_path_overridden: !!OUT_PATH_ENV
        },
        fatal: fatal
          ? { message: redact(fatal.message || fatal),
              stack: redact(fatal.stack || '(no stack)') }
          : null,
        errors: errors,
        trace: trace
      }, null, 2));
      print('[maestrina] ' + kind + ' diagnostics written: ' + diagPath);
      if (kind === 'crash') {
        print('[maestrina] Please send this crash file back to the Maestrina ' +
              'maintainer — it contains no collected data, only the execution ' +
              'trace needed to fix the problem.');
      }
      return diagPath;
    } catch (e2) {
      print('[maestrina] could not write ' + kind + ' diagnostics: ' +
            redact(e2 && e2.message ? e2.message : e2));
      return null;
    }
  }

  try { // fatal-crash guard — on any uncaught error, write a crash report

  // --------------------------------------------------------------------- //
  // Small helpers                                                         //
  // --------------------------------------------------------------------- //
  function num(v) {
    if (v === null || v === undefined) return null;
    const n = Number(v);
    return isFinite(n) ? n : null;
  }
  function intOrNull(v) {
    const n = num(v);
    return n === null ? null : Math.round(n);
  }
  function round(v, places) {
    const n = num(v);
    if (n === null) return null;
    const f = Math.pow(10, places === undefined ? 1 : places);
    return Math.round(n * f) / f;
  }
  function tsSeconds(ts) {
    // BSON Timestamp across driver versions: getHighBits() / .t / {$timestamp}
    if (!ts) return null;
    if (typeof ts.getHighBits === 'function') return ts.getHighBits();
    if (typeof ts.t === 'number') return ts.t;
    if (ts.$timestamp && typeof ts.$timestamp.t === 'number') return ts.$timestamp.t;
    return null;
  }
  function get(obj, dottedPath) {
    let cur = obj;
    for (const k of dottedPath.split('.')) {
      if (cur === null || cur === undefined) return null;
      cur = cur[k];
    }
    return cur === undefined ? null : cur;
  }

  // --------------------------------------------------------------------- //
  // Pseudonymization (sequential labels; map retained client-side only)   //
  // --------------------------------------------------------------------- //
  const pseudoMap = { namespaces: {}, hosts: {}, database_names: {}, index_names: {} };
  const pseudoCounters = { namespaces: 0, hosts: 0, database_names: 0, index_names: 0 };

  function label(kind, prefix, real) {
    if (!PSEUDO || real === null || real === undefined) return real;
    const bucket = pseudoMap[kind];
    if (!(real in bucket)) {
      pseudoCounters[kind] += 1;
      const n = pseudoCounters[kind];
      bucket[real] = kind === 'hosts'
        ? prefix + '_' + String.fromCharCode(64 + ((n - 1) % 26) + 1) + (n > 26 ? Math.ceil(n / 26) : '')
        : prefix + '_' + String(n).padStart(3, '0');
    }
    return bucket[real];
  }
  const pseudoNs = (ns) => label('namespaces', 'ns', ns);
  const pseudoHost = (h) => label('hosts', 'host', h);
  const pseudoDb = (d) => label('database_names', 'db', d);
  const pseudoIdx = (i) => label('index_names', 'idx', i);

  // --------------------------------------------------------------------- //
  // Topology detection                                                    //
  // --------------------------------------------------------------------- //
  phase = 'topology_detection';
  const admin = db.getSiblingDB('admin');
  const hello = attempt('hello', () => admin.runCommand({ hello: 1 })) || {};
  const isMongos = hello.msg === 'isdbgrid';
  const setName = hello.setName || null;
  const topology = isMongos ? 'sharded_cluster' : (setName ? 'replica_set' : 'standalone');
  envInfo.topology = topology;

  const buildInfo = attempt('buildInfo', () => admin.runCommand({ buildInfo: 1 })) || {};
  const mongodbVersion = buildInfo.version || 'unknown';
  envInfo.mongodb_version = mongodbVersion;

  // --------------------------------------------------------------------- //
  // serverStatus — two samples for real ops/s deltas                      //
  // --------------------------------------------------------------------- //
  function takeServerStatus() {
    return attempt('serverStatus', () => admin.runCommand({ serverStatus: 1 }));
  }

  phase = 'sampling';
  const startedAt = new Date();
  const ss1 = takeServerStatus();
  let ss2 = null;
  let sampleOffset = null;

  if (ss1 && SAMPLE_SECONDS > 0) {
    print('[maestrina] first sample taken; waiting ' + SAMPLE_SECONDS +
          's for the second sample (set MAESTRINA_SAMPLE_SECONDS to change)...');
    sleep(SAMPLE_SECONDS * 1000);
    ss2 = takeServerStatus();
    if (ss2) sampleOffset = SAMPLE_SECONDS;
  }
  const ss = ss2 || ss1 || {};
  const uptimeSeconds = intOrNull(ss.uptime);

  function counterRate(dottedPath) {
    // two_sample_delta when both samples exist; otherwise uptime average
    const v2 = num(get(ss2 || {}, dottedPath));
    const v1 = num(get(ss1 || {}, dottedPath));
    if (ss2 && v2 !== null && v1 !== null && sampleOffset > 0) {
      return round((v2 - v1) / sampleOffset, 2);
    }
    const v = num(get(ss, dottedPath));
    if (v !== null && uptimeSeconds && uptimeSeconds > 0) {
      return round(v / uptimeSeconds, 2);
    }
    return null;
  }
  const ratesMethod = (ss2 && sampleOffset) ? 'two_sample_delta' : 'uptime_average';

  // --------------------------------------------------------------------- //
  // WORKLOAD section                                                      //
  // --------------------------------------------------------------------- //
  phase = 'workload';
  const opsPerSec = {
    insert: counterRate('opcounters.insert'),
    query: counterRate('opcounters.query'),
    update: counterRate('opcounters.update'),
    delete: counterRate('opcounters.delete'),
    getmore: counterRate('opcounters.getmore'),
    command: counterRate('opcounters.command')
  };
  const reads = (opsPerSec.query || 0) + (opsPerSec.getmore || 0);
  const writes = (opsPerSec.insert || 0) + (opsPerSec.update || 0) + (opsPerSec.delete || 0);
  const readWriteRatio = writes > 0 ? round(reads / writes, 2) : null;

  // Database and namespace sizes
  const listDbs = attempt('listDatabases', () =>
    admin.runCommand({ listDatabases: 1 })) || { databases: [] };
  const userDbs = (listDbs.databases || [])
    .map((d) => d.name)
    .filter((n) => ['admin', 'local', 'config'].indexOf(n) === -1);

  let totalDataBytes = 0, totalStorageBytes = 0, totalIndexBytes = 0;
  let fsUsed = null, fsTotal = null;
  const namespaces = [];
  const unusedIndexes = [];

  for (const dbName of userDbs) {
    const dbh = db.getSiblingDB(dbName);

    const dstats = attempt('dbStats:' + pseudoDb(dbName), () => dbh.runCommand({ dbStats: 1 }));
    if (dstats) {
      totalDataBytes += num(dstats.dataSize) || 0;
      totalStorageBytes += num(dstats.storageSize) || 0;
      totalIndexBytes += num(dstats.indexSize) || 0;
      if (fsUsed === null && num(dstats.fsUsedSize) !== null) {
        fsUsed = num(dstats.fsUsedSize);
        fsTotal = num(dstats.fsTotalSize);
      }
    }

    const collInfos = attempt('listCollections:' + pseudoDb(dbName), () =>
      dbh.getCollectionInfos({ type: 'collection' })) || [];

    for (const info of collInfos) {
      const collName = info.name;
      if (collName.indexOf('system.') === 0) continue;
      const ns = dbName + '.' + collName;

      // Sizes via $collStats (merged across shards on mongos)
      const statDocs = attempt('$collStats:' + pseudoNs(ns), () =>
        dbh.getCollection(collName)
          .aggregate([{ $collStats: { storageStats: {} } }])
          .toArray()) || [];
      if (statDocs.length > 0) {
        let dataB = 0, idxB = 0, docs = 0, seen = false;
        for (const sdoc of statDocs) {
          const st = sdoc.storageStats || {};
          if (num(st.size) !== null) { dataB += num(st.size); seen = true; }
          if (num(st.totalIndexSize) !== null) idxB += num(st.totalIndexSize);
          if (num(st.count) !== null) docs += num(st.count);
        }
        namespaces.push({
          namespace: pseudoNs(ns),
          data_size_bytes: seen ? Math.round(dataB) : null,
          index_size_bytes: Math.round(idxB),
          document_count: Math.round(docs),
          _idxSizes: statDocs.map((d) => (d.storageStats || {}).indexSizes || {})
        });
      }

      // Index usage via $indexStats (per-shard docs summed on mongos)
      const idxDocs = attempt('$indexStats:' + pseudoNs(ns), () =>
        dbh.getCollection(collName)
          .aggregate([{ $indexStats: {} }])
          .toArray()) || [];
      const byIndex = {};
      for (const d of idxDocs) {
        const name = d.name;
        if (!byIndex[name]) byIndex[name] = { ops: 0, since: null };
        byIndex[name].ops += num(get(d, 'accesses.ops')) || 0;
        const since = get(d, 'accesses.since');
        const sinceIso = since ? new Date(since).toISOString() : null;
        if (sinceIso && (!byIndex[name].since || sinceIso < byIndex[name].since)) {
          byIndex[name].since = sinceIso;
        }
      }
      for (const idxName in byIndex) {
        if (idxName === '_id_') continue;
        if (byIndex[idxName].ops === 0) {
          // size from the last collected storageStats.indexSizes
          let sizeB = null;
          const nsEntry = namespaces[namespaces.length - 1];
          if (nsEntry && nsEntry.namespace === pseudoNs(ns)) {
            let s = 0, found = false;
            for (const m of nsEntry._idxSizes) {
              if (num(m[idxName]) !== null) { s += num(m[idxName]); found = true; }
            }
            if (found) sizeB = Math.round(s);
          }
          unusedIndexes.push({
            namespace: pseudoNs(ns),
            index: pseudoIdx(idxName),
            accesses_ops: 0,
            accesses_since: byIndex[idxName].since,
            size_bytes: sizeB
          });
        }
      }
    }
  }
  // drop the internal helper field and keep only the biggest namespaces
  for (const n of namespaces) delete n._idxSizes;
  namespaces.sort((a, b) =>
    ((b.data_size_bytes || 0) + (b.index_size_bytes || 0)) -
    ((a.data_size_bytes || 0) + (a.index_size_bytes || 0)));
  const topNamespaces = namespaces.slice(0, TOP_NAMESPACES_LIMIT);
  unusedIndexes.sort((a, b) => (b.size_bytes || 0) - (a.size_bytes || 0));
  const unusedTop = unusedIndexes.slice(0, UNUSED_INDEXES_LIMIT);

  // Working set proxy: WiredTiger cache occupancy (not meaningful on mongos)
  const cacheConfigured = intOrNull(get(ss, 'wiredTiger.cache.maximum bytes configured'));
  const cacheInUse = intOrNull(get(ss, 'wiredTiger.cache.bytes currently in the cache'));
  const cacheDirty = num(get(ss, 'wiredTiger.cache.tracked dirty bytes in the cache'));

  const workload = {
    available: true,
    unavailable_reason: null,
    data: {
      rates: {
        method: ratesMethod,
        ops_per_sec: opsPerSec,
        read_write_ratio: readWriteRatio
      },
      storage: {
        data_size_bytes: Math.round(totalDataBytes),
        storage_size_bytes: Math.round(totalStorageBytes),
        index_size_bytes: Math.round(totalIndexBytes),
        growth_30d_percent: null
      },
      working_set_estimate_bytes: cacheInUse,
      top_namespaces: topNamespaces
    }
  };

  // --------------------------------------------------------------------- //
  // AVAILABILITY section                                                  //
  // --------------------------------------------------------------------- //
  phase = 'availability';
  let replication = { max_lag_seconds: null, members: [] };
  let oplogWindowHours = null;

  if (topology === 'replica_set') {
    const rsStatus = attempt('replSetGetStatus', () =>
      admin.runCommand({ replSetGetStatus: 1 }));
    if (rsStatus && rsStatus.members) {
      let primaryOptime = null;
      for (const m of rsStatus.members) {
        if (m.stateStr === 'PRIMARY') primaryOptime = tsSeconds(get(m, 'optime.ts'));
      }
      let maxLag = null;
      const members = [];
      for (const m of rsStatus.members) {
        let lag = null;
        if (m.stateStr === 'SECONDARY' && primaryOptime !== null) {
          const sec = tsSeconds(get(m, 'optime.ts'));
          if (sec !== null) lag = round(Math.max(0, primaryOptime - sec), 1);
          if (lag !== null && (maxLag === null || lag > maxLag)) maxLag = lag;
        }
        members.push({ member: pseudoHost(m.name), state: m.stateStr, lag_seconds: lag });
      }
      replication = { max_lag_seconds: maxLag, members: members };
    }

    oplogWindowHours = attempt('oplogWindow', () => {
      const local = db.getSiblingDB('local');
      const first = local.getCollection('oplog.rs')
        .find({}, { ts: 1 }).sort({ $natural: 1 }).limit(1).toArray()[0];
      const last = local.getCollection('oplog.rs')
        .find({}, { ts: 1 }).sort({ $natural: -1 }).limit(1).toArray()[0];
      const a = first ? tsSeconds(first.ts) : null;
      const b = last ? tsSeconds(last.ts) : null;
      return (a !== null && b !== null) ? round((b - a) / 3600, 1) : null;
    });
  }

  // Tickets: 7.x+ exposes queues.execution; older versions use
  // wiredTiger.concurrentTransactions. Try both. Null on mongos.
  const ticketsRead = intOrNull(get(ss, 'queues.execution.read.available')) !== null
    ? intOrNull(get(ss, 'queues.execution.read.available'))
    : intOrNull(get(ss, 'wiredTiger.concurrentTransactions.read.available'));
  const ticketsWrite = intOrNull(get(ss, 'queues.execution.write.available')) !== null
    ? intOrNull(get(ss, 'queues.execution.write.available'))
    : intOrNull(get(ss, 'wiredTiger.concurrentTransactions.write.available'));

  const connCurrent = intOrNull(get(ss, 'connections.current'));
  const connAvailable = intOrNull(get(ss, 'connections.available'));
  const connUtil = (connCurrent !== null && connAvailable !== null &&
                    (connCurrent + connAvailable) > 0)
    ? round(100 * connCurrent / (connCurrent + connAvailable), 1)
    : null;

  const diskUsedPercent = (fsUsed !== null && fsTotal && fsTotal > 0)
    ? round(100 * fsUsed / fsTotal, 1)
    : null;

  const availability = {
    available: true,
    unavailable_reason: null,
    data: {
      replication: replication,
      oplog_window_hours: oplogWindowHours,
      elections_last_30d: null,   // atlas_api mode only (events API)
      restarts_last_30d: null,    // atlas_api mode only
      tickets: { read_available: ticketsRead, write_available: ticketsWrite },
      connections: {
        current: connCurrent,
        available: connAvailable,
        utilization_percent: connUtil
      },
      disk: {
        space_used_percent: diskUsedPercent,
        util_percent_max_30d: null // atlas_api mode only (hardware metrics)
      },
      page_faults_per_sec: counterRate('extra_info.page_faults')
    }
  };

  // --------------------------------------------------------------------- //
  // EFFICIENCY section                                                    //
  // --------------------------------------------------------------------- //
  function cumulativeRatio(numPath, denPath) {
    // Prefer deltas between samples; fall back to cumulative ratio
    const n2 = num(get(ss2 || {}, numPath)), n1 = num(get(ss1 || {}, numPath));
    const d2 = num(get(ss2 || {}, denPath)), d1 = num(get(ss1 || {}, denPath));
    if (ss2 && n2 !== null && n1 !== null && d2 !== null && d1 !== null && (d2 - d1) > 0) {
      return round((n2 - n1) / (d2 - d1), 1);
    }
    const n = num(get(ss, numPath)), d = num(get(ss, denPath));
    return (n !== null && d !== null && d > 0) ? round(n / d, 1) : null;
  }

  phase = 'efficiency';
  const efficiency = {
    available: true,
    unavailable_reason: null,
    data: {
      query_targeting: {
        keys_scanned_per_returned:
          cumulativeRatio('metrics.queryExecutor.scanned', 'metrics.document.returned'),
        objects_scanned_per_returned:
          cumulativeRatio('metrics.queryExecutor.scannedObjects', 'metrics.document.returned'),
        source: 'server_status_global'
      },
      scan_and_order_per_sec: counterRate('metrics.operation.scanAndOrder'),
      cache: {
        configured_bytes: cacheConfigured,
        in_cache_bytes: cacheInUse,
        dirty_percent: (cacheDirty !== null && cacheConfigured && cacheConfigured > 0)
          ? round(100 * cacheDirty / cacheConfigured, 1) : null,
        fill_percent: (cacheInUse !== null && cacheConfigured && cacheConfigured > 0)
          ? round(100 * cacheInUse / cacheConfigured, 1) : null
      },
      unused_indexes: unusedTop,
      performance_advisor: null // atlas_api mode only
    }
  };

  // --------------------------------------------------------------------- //
  // FINANCIAL and ALERT_HYGIENE — explicitly unavailable in mongosh mode  //
  // --------------------------------------------------------------------- //
  const requiresApi = 'requires atlas_api mode (read-only API key)';
  const financial = { available: false, unavailable_reason: requiresApi, data: null };
  const alertHygiene = { available: false, unavailable_reason: requiresApi, data: null };

  // --------------------------------------------------------------------- //
  // SHARDING — config metadata only, via mongos                           //
  // Approach credited to Felipe Scabral's msizer-mongodb                  //
  // (https://github.com/felipesscabral/msizer-mongodb). Null means        //
  // "not sharded", not "unavailable".                                     //
  // --------------------------------------------------------------------- //
  phase = 'sharding';
  let sharding = null;
  if (isMongos) {
    sharding = attempt('sharding', () => {
      const config = db.getSiblingDB('config');

      const shards = attempt('config.shards', () =>
        config.getCollection('shards').find({}).toArray()) || [];

      const balancerDoc = attempt('config.settings.balancer', () =>
        config.getCollection('settings').findOne({ _id: 'balancer' }));
      const balancerEnabled = balancerDoc ? !(balancerDoc.stopped === true) : true;

      const balancerStatus = attempt('balancerStatus', () =>
        admin.runCommand({ balancerStatus: 1 }));
      const balancerRunning = balancerStatus
        ? (balancerStatus.inBalancerRound === true) : null;

      // 'partitioned' flag was removed in 6.0; unsplittable added in 8.0.
      // Count collections tracked in config.collections excluding
      // unsplittable (8.0+) and dropped legacy entries.
      const shardedCollectionsCount = attempt('config.collections', () =>
        config.getCollection('collections').countDocuments({
          _id: { $not: /^config\./ },
          $and: [
            { $or: [{ unsplittable: { $exists: false } }, { unsplittable: false }] },
            { $or: [{ dropped: { $exists: false } }, { dropped: false }] }
          ]
        }));

      const jumboCount = attempt('config.chunks.jumbo', () =>
        config.getCollection('chunks').countDocuments({ jumbo: true }));

      // Per-shard distribution: prefer $shardedDataDistribution (6.0.3+),
      // fall back to chunk counts from config metadata.
      const perShard = {};
      for (const s of shards) {
        perShard[s._id] = { data_size_bytes: null, chunks_count: null };
      }

      const sdd = attempt('$shardedDataDistribution', () =>
        admin.aggregate([{ $shardedDataDistribution: {} }]).toArray());
      let orphanedTotal = null;
      if (sdd && sdd.length > 0) {
        orphanedTotal = 0;
        for (const collDoc of sdd) {
          for (const sh of (collDoc.shards || [])) {
            const id = sh.shardName;
            if (!perShard[id]) perShard[id] = { data_size_bytes: null, chunks_count: null };
            if (num(sh.ownedSizeBytes) !== null) {
              perShard[id].data_size_bytes =
                (perShard[id].data_size_bytes || 0) + num(sh.ownedSizeBytes);
            }
            if (num(sh.numOrphanedDocs) !== null) {
              orphanedTotal += num(sh.numOrphanedDocs);
            }
          }
        }
        orphanedTotal = Math.round(orphanedTotal);
      }

      // Chunk counts per shard (chunks are keyed by collection UUID in 5.0+,
      // but the 'shard' field is stable across versions)
      attempt('config.chunks.perShard', () => {
        const counts = config.getCollection('chunks').aggregate([
          { $group: { _id: '$shard', n: { $sum: 1 } } }
        ]).toArray();
        for (const c of counts) {
          if (!perShard[c._id]) perShard[c._id] = { data_size_bytes: null, chunks_count: null };
          perShard[c._id].chunks_count = c.n;
        }
        return true;
      });

      // Assemble distribution + imbalance
      const dist = [];
      let sizes = [];
      let totalSize = 0;
      for (const id in perShard) {
        const e = perShard[id];
        if (e.data_size_bytes !== null) {
          e.data_size_bytes = Math.round(e.data_size_bytes);
          sizes.push(e.data_size_bytes);
          totalSize += e.data_size_bytes;
        }
      }
      for (const id in perShard) {
        const e = perShard[id];
        dist.push({
          shard: pseudoHost(id),
          data_size_bytes: e.data_size_bytes,
          data_percent: (e.data_size_bytes !== null && totalSize > 0)
            ? round(100 * e.data_size_bytes / totalSize, 1) : null,
          chunks_count: e.chunks_count !== null ? intOrNull(e.chunks_count) : null
        });
      }
      let imbalance = null;
      if (sizes.length > 1) {
        const mean = totalSize / sizes.length;
        if (mean > 0) {
          imbalance = round(100 * (Math.max.apply(null, sizes) -
                                   Math.min.apply(null, sizes)) / mean, 1);
        }
      }

      return {
        shards_count: shards.length,
        balancer_enabled: balancerEnabled,
        balancer_running: balancerRunning,
        sharded_collections_count: intOrNull(shardedCollectionsCount),
        jumbo_chunks_count: intOrNull(jumboCount),
        data_distribution: dist,
        orphaned_docs_total: orphanedTotal,
        imbalance_percent: imbalance
      };
    });
  }

  // --------------------------------------------------------------------- //
  // BASELINE — injected via side file, never typed by the client          //
  // --------------------------------------------------------------------- //
  phase = 'baseline';
  let baseline = null;
  if (BASELINE_FILE) {
    baseline = attempt('baseline_file', () => {
      const raw = fs.readFileSync(BASELINE_FILE, 'utf8');
      const b = JSON.parse(raw);
      if (!b.source || !b.created_at || !b.bands || !b.checkpoints) {
        throw new Error('baseline file missing required fields ' +
          '(source, created_at, bands, checkpoints)');
      }
      return b;
    });
  }

  // --------------------------------------------------------------------- //
  // Assemble output per contract v2.1.0                                   //
  // --------------------------------------------------------------------- //
  phase = 'assemble_output';
  const clusterNameReal = setName ||
    (isMongos ? 'sharded-cluster' : (hello.me || 'standalone'));
  // Cluster name is NEVER pseudonymized: it is the navigation key used to
  // locate findings and point the client at the right cluster when there
  // are many. Hosts/namespaces/indexes remain maskable via MAESTRINA_PSEUDO.
  const clusterName = clusterNameReal;
  const generatedAt = new Date();

  const output = {
    maestrina: {
      schema_version: SCHEMA_VERSION,
      collector: { name: 'maestrina_collect.js', version: VERSION },
      collection_mode: 'mongosh',
      generated_at: generatedAt.toISOString(),
      collection_window: {
        start: startedAt.toISOString(),
        end: generatedAt.toISOString(),
        second_sample_offset_seconds: sampleOffset,
        server_uptime_seconds: uptimeSeconds
      }
    },
    compliance_manifest: {
      statement: 'This file contains only operational metadata and statistics ' +
        '(counters, sizes, rates, configuration flags). It contains no business ' +
        'data, no document contents, no query predicate values, and no ' +
        'personally identifiable information.',
      categories_collected: [
        'server_status_counters',
        'replication_status',
        'storage_and_index_sizes',
        'index_usage_statistics',
        'connection_statistics',
        'cluster_configuration'
      ],
      categories_excluded: [
        'document_contents',
        'query_predicate_values',
        'user_accounts_and_credentials',
        'application_business_data',
        'personally_identifiable_information'
      ],
      pseudonymization: {
        enabled: PSEUDO,
        method: PSEUDO ? 'sequential_labels' : null,
        applies_to: PSEUDO
          ? ['namespaces', 'hosts', 'index_names', 'database_names']
          : []
      }
    },
    target: {
      cluster_name: clusterName,
      mongodb_version: mongodbVersion,
      topology: topology,
      atlas: null
    },
    baseline: baseline,
    clusters: [
      {
        name: clusterName,
        workload: workload,
        availability: availability,
        efficiency: efficiency,
        financial: financial,
        alert_hygiene: alertHygiene,
        sharding: sharding
      }
    ],
    errors: errors
  };

  // --------------------------------------------------------------------- //
  // Write output (+ pseudonym map, retained client-side)                  //
  // --------------------------------------------------------------------- //
  phase = 'write_output';
  const stamp = generatedAt.toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const safeName = String(clusterName).replace(/[^A-Za-z0-9_-]/g, '_');
  const outPath = OUT_PATH_ENV ||
    path.join(process.cwd(), 'maestrina_output_' + safeName + '_' + stamp + '.json');

  fs.writeFileSync(outPath, JSON.stringify(output, null, 2));
  print('');
  print('[maestrina] output written: ' + outPath);
  print('[maestrina] mode=mongosh  rates.method=' + ratesMethod +
        '  topology=' + topology + '  errors=' + errors.length);

  if (PSEUDO) {
    const mapPath = outPath.replace(/\.json$/, '') + '.pseudonym_map.json';
    fs.writeFileSync(mapPath, JSON.stringify(pseudoMap, null, 2));
    print('[maestrina] pseudonym map written: ' + mapPath);
    print('[maestrina] KEEP THE MAP FILE — do NOT send it with the output.');
  }
  print('[maestrina] Inspect the JSON before sending. It contains only ' +
        'operational metadata — see the compliance_manifest section inside.');

  phase = 'done';
  if (DEBUG) writeDiagnostics('debug', null);

  } catch (fatal) {
    // A single-command failure never lands here (attempt() absorbs those);
    // this is a genuine collector bug or an environment problem. Write a
    // crash report so the failure is fixable without access to this
    // environment, and rethrow so mongosh exits non-zero.
    writeDiagnostics('crash', fatal);
    throw fatal;
  }
})();

// END OF FILE — maestrina_collect.js v2.1.0
